title: Hemant Rathore's Technical Blog
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
description: Exploring Cloud
url: https://hmntrathore.github.io
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
